language: c

os:
 - linux
 - osx

env:
 - NODE_VERSION=6
 - NODE_VERSION=8
 - NODE_VERSION=9

matrix:
  fast_finish: true

branches:
  only:
    - master
    - beta

before_install:
  - nvm install $NODE_VERSION
  - nvm use --delete-prefix $NODE_VERSION || echo
  - if [[ $(npm -v) != 5* ]]; then npm i -g npm@5; fi;
  - npm install
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        export DISPLAY=:99.0;
        sh -e /etc/init.d/xvfb start;
        sleep 8;
    fi

script:
 - npm test

cache:
  directories:
    - node_modules

notifications:
  email:
    on_success: never
    on_failure: change
